name: Bug report
description: Signaler un bug
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problème
      description: Décris le bug clairement
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Étapes pour reproduire
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Résultat attendu
    validations:
      required: true
